[server]
enableCORS = false
enableXsrfProtection = false

[deprecation]
showfileUploaderEncoding = false

[client]
toolbarMode = "minimal"

[watcher]
# Increase the inotify limit to a higher value (e.g., 524288)
# This prevents "inotify instance limit reached" errors on large projects.
inotify_max_user_watches = 524288
